### PR TITLE
[chore] fix CI and substrate deps

### PR DESCRIPTION
**Pull request by shekohex**
- `frame-system` crate should be `optional` by default, and only enabled on substrate.
- fixed the docs and comments
- added CI steps to check the build for each proposal implementation (separately)

### CODE REVIEW

**Comment by Nutomic** [comment]
Could you also include new metadata from protocol-substrate in the release? I tried to do that locally but ended up with strange import errors.

**Comment by shekohex** [comment]
> Could you also include new metadata from protocol-substrate in the release? I tried to do that locally but ended up with strange import errors.

You should really use the tangle runtime for that, I do not think we will need to use the protocol-substrate metadata on its own, anymore.

**Review by drewstone — APPROVED** [review]
We can also remove all the ink proposals too.

**Comment by Nutomic** [comment]
> You should really use the tangle runtime for that, I do not think we will need to use the protocol-substrate metadata on its own, anymore.

What do you mean by this? I think in any case its necessary to update the metadata in this repo in order to interact with my changes in dkg-substrate repo (I mistyped the repo name in my last comment).

**Comment by shekohex** [comment]
> > You should really use the tangle runtime for that, I do not think we will need to use the protocol-substrate metadata on its own, anymore.
> 
> What do you mean by this? I think in any case its necessary to update the metadata in this repo in order to interact with my changes in dkg-substrate repo (I mistyped the repo name in my last comment).

Yes, we can do that in a new PR to update the `dkg-substrate` metadata.

**Pull request merged**
